[tool.poetry]
name = "health-svc"
version = "0.1.0"
description = "DORA micro-service: health monitoring"
authors = ["yujie <s323024@studenti.polito.it>"]

packages = [{ include = "app" }]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.111.0"
uvicorn = {extras = ["standard"], version = "^0.30.1"}
redis = "^5.0.4"
paho-mqtt = ">=2.1,<3"
cryptography = "^42.0.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
